#!/bin/bash

echo 'Updating version in src/ChessBoard.svelte'
sed -i -r "s/[0-9]+\.[0-9]+\.[0-9]+/`node -e "console.log(require('./package.json').version)"`/" src/ChessBoard.svelte

echo 'Updating version in README.md'
sed -i -r "s/[0-9]+\.[0-9]+\.[0-9]+/`node -e "console.log(require('./package.json').version)"`/" README.md

echo 'Done'